CREATE TABLE FIDE_USUARIOS_TB (
    USUARIOS_ID_USUARIO_PK INT,
    Nombre VARCHAR(50),
    Apellido_1 VARCHAR(50),
    Apellido_2 VARCHAR(50),
    Correo VARCHAR(100),
    Telefono VARCHAR(20),
    Contrasena VARCHAR(50),
    Rol VARCHAR(20) CHECK (Rol IN ('Cliente', 'Empleado', 'Administrador')),
    Contacto_emergencia VARCHAR(100),
    CONSTRAINT usu_pk PRIMARY KEY (USUARIOS_ID_USUARIO_PK) USING INDEX (CREATE INDEX USUARIOS_ID_USUARIO_IDX ON FIDE_USUARIOS_TB (USUARIOS_ID_USUARIO_PK))
);

CREATE TABLE FIDE_CUENTAS_TB (
    CUENTAS_ID_CUENTA_PK INT,
    Id_usuario INT,
    Tipo_cuenta VARCHAR(20) CHECK (Tipo_cuenta IN ('Ahorro', 'Corriente')),
    Saldo DECIMAL(12, 2),
    Fecha_creacion DATE,
    Estado VARCHAR(20) CHECK (Estado IN ('Activa', 'Inactiva', 'Cancelada')),
    CONSTRAINT cue_pk PRIMARY KEY (CUENTAS_ID_CUENTA_PK) USING INDEX (CREATE INDEX CUENTAS_ID_CUENTA_IDX ON FIDE_CUENTAS_TB (CUENTAS_ID_CUENTA_PK)),
    CONSTRAINT cue_fk FOREIGN KEY (Id_usuario) REFERENCES FIDE_USUARIOS_TB (USUARIOS_ID_USUARIO_PK)
);

CREATE TABLE FIDE_MOVIMIENTOS_CUENTA_TB (
    MOVIMIENTOS_CUENTA_ID_MOVIMIENTO_PK INT,
    Id_cuenta INT,
    Tipo_movimiento VARCHAR(20) CHECK (Tipo_movimiento IN ('Depósito', 'Retiro', 'Transferencia', 'Pago')),
    Monto DECIMAL(10, 2),
    Fecha DATE,
    Detalle VARCHAR(255),
    CONSTRAINT mov_pk PRIMARY KEY (MOVIMIENTOS_CUENTA_ID_MOVIMIENTO_PK) USING INDEX (CREATE INDEX MOVIMIENTOS_CUENTA_ID_MOVIMIENTO_IDX ON FIDE_MOVIMIENTOS_CUENTA_TB (MOVIMIENTOS_CUENTA_ID_MOVIMIENTO_PK)),
    CONSTRAINT mov_fk FOREIGN KEY (Id_cuenta) REFERENCES FIDE_CUENTAS_TB (CUENTAS_ID_CUENTA_PK)
);

CREATE TABLE FIDE_TARJETAS_DEBITO_TB (
    TARJETAS_DEBITO_ID_TARJETA_DEBITO_PK INT,
    Id_cuenta INT,
    Fecha_vencimiento DATE,
    Limite_credito DECIMAL(10, 2),
    Saldo_pendiente DECIMAL(10, 2),
    Fecha_cobro DATE,
    Estado VARCHAR(20) CHECK (Estado IN ('Activa', 'Inactiva', 'Cancelada')),
    CONSTRAINT td_pk PRIMARY KEY (TARJETAS_DEBITO_ID_TARJETA_DEBITO_PK) USING INDEX (CREATE INDEX TARJETAS_DEBITO_ID_TARJETA_DEBITO_IDX ON FIDE_TARJETAS_DEBITO_TB (TARJETAS_DEBITO_ID_TARJETA_DEBITO_PK)),
    CONSTRAINT td_fk FOREIGN KEY (Id_cuenta) REFERENCES FIDE_CUENTAS_TB (CUENTAS_ID_CUENTA_PK)
);

CREATE TABLE FIDE_PENSIONES_TB (
    PENSIONES_ID_PENSION_PK INT,
    Id_usuario INT,
    Id_cuenta INT,
    Monto_ahorro_mensual DECIMAL(10, 2),
    Fecha_inicio DATE,
    Fecha_fin DATE,
    Estado VARCHAR(20),
    CONSTRAINT pens_pk PRIMARY KEY (PENSIONES_ID_PENSION_PK) USING INDEX (CREATE INDEX PENSIONES_ID_PENSION_IDX ON FIDE_PENSIONES_TB (PENSIONES_ID_PENSION_PK)),
    CONSTRAINT pens_fk1 FOREIGN KEY (Id_usuario) REFERENCES FIDE_USUARIOS_TB (USUARIOS_ID_USUARIO_PK),
    CONSTRAINT pens_fk2 FOREIGN KEY (Id_cuenta) REFERENCES FIDE_CUENTAS_TB (CUENTAS_ID_CUENTA_PK)
);

CREATE TABLE FIDE_PRESTAMOS_TB (
    PRESTAMOS_ID_PRESTAMO_PK INT,
    Id_usuario INT,
    Monto DECIMAL(10, 2),
    Tasa_interes DECIMAL(5, 2),
    Plazo INT,
    Fecha_inicio DATE,
    Fecha_fin DATE,
    CONSTRAINT prest_pk PRIMARY KEY (PRESTAMOS_ID_PRESTAMO_PK) USING INDEX (CREATE INDEX PRESTAMOS_ID_PRESTAMO_IDX ON FIDE_PRESTAMOS_TB (PRESTAMOS_ID_PRESTAMO_PK)),
    CONSTRAINT prest_fk FOREIGN KEY (Id_usuario) REFERENCES FIDE_USUARIOS_TB (USUARIOS_ID_USUARIO_PK)
);

CREATE TABLE FIDE_SOLICITUDES_TB (
    SOLICITUDES_ID_SOLICITUD_PK INT,
    Id_usuario INT,
    Fecha_solicitud DATE,
    Estado VARCHAR(20) CHECK (Estado IN ('Pendiente', 'Aprobada', 'Rechazada')),
    Justificacion VARCHAR(255),
    CONSTRAINT sol_pk PRIMARY KEY (SOLICITUDES_ID_SOLICITUD_PK) USING INDEX (CREATE INDEX SOLICITUDES_ID_SOLICITUD_IDX ON FIDE_SOLICITUDES_TB (SOLICITUDES_ID_SOLICITUD_PK)),
    CONSTRAINT sol_fk FOREIGN KEY (Id_usuario) REFERENCES FIDE_USUARIOS_TB (USUARIOS_ID_USUARIO_PK)
);

CREATE TABLE FIDE_TARJETAS_CREDITO_TB (
    TARJETAS_CREDITO_ID_TARJETA_CREDITO_PK INT,
    Id_usuario INT,
    Fecha_vencimiento DATE,
    Limite_credito DECIMAL(10, 2),
    Saldo_pendiente DECIMAL(10, 2),
    Fecha_cobro DATE,
    Estado VARCHAR(20) CHECK (Estado IN ('Activa', 'Inactiva', 'Cancelada')),
    CONSTRAINT tc_pk PRIMARY KEY (TARJETAS_CREDITO_ID_TARJETA_CREDITO_PK) USING INDEX (CREATE INDEX TARJETAS_CREDITO_ID_TARJETA_CREDITO_IDX ON FIDE_TARJETAS_CREDITO_TB (TARJETAS_CREDITO_ID_TARJETA_CREDITO_PK)),
    CONSTRAINT tc_fk FOREIGN KEY (Id_usuario) REFERENCES FIDE_USUARIOS_TB (USUARIOS_ID_USUARIO_PK)
);

CREATE TABLE FIDE_BIENES_ADJUDICADOS_TB (
    BIENES_ADJUDICADOS_ID_BIEN_PK INT,
    Tipo_bien VARCHAR(50),
    Descripcion VARCHAR(255),
    Valor DECIMAL(10, 2),
    Estado VARCHAR(20) CHECK (Estado IN ('Disponible', 'Vendido')),
    CONSTRAINT bienes_pk PRIMARY KEY (BIENES_ADJUDICADOS_ID_BIEN_PK) USING INDEX (CREATE INDEX BIENES_ADJUDICADOS_ID_BIEN_IDX ON FIDE_BIENES_ADJUDICADOS_TB (BIENES_ADJUDICADOS_ID_BIEN_PK))
);




